version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - db_network

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - db_network

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - dockerpath:/var/lib/postgresql/data
    networks:
      - db_network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017  
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME} 
    volumes:
      - mongo_data2:/data/db
    networks:
      - db_network

networks:
  db_network:
    name: db_network
    driver: bridge

volumes:
  mongo_data2:
  dockerpath:
